### ISSUE TITLE
about aux_loss

### ISSUE THREAD

**Issue by enterhuiche** [davidmrau/mixture-of-experts#10]
Hello, I would like to ask what will be the overall trend of aux_loss training? After I added MOE to my model, although the loss decreased, the aux_loss kept fluctuating
![捕获](https://user-images.githubusercontent.com/19527361/148336990-56c41481-ee19-45fc-8d87-733f71311124.PNG)
.

**Comment by davidmrau** [comment]
In general, it would be desirable how have the auxiliary loss decreasing. You might want to increase the `loss_coef` that is passed in the `forward` [here](https://github.com/davidmrau/mixture-of-experts/blob/9739be4e52b3d8709fb8e1f94ee0dbfab9b4a1a1/moe.py#L255), to minimize the loss further if you have the feeling the distribution of the experts is extremely unbalanced. To check this you could plot the gating distribution and load during training or inference [here](https://github.com/davidmrau/mixture-of-experts/blob/9739be4e52b3d8709fb8e1f94ee0dbfab9b4a1a1/moe.py#L267). Hope this helps.

**Comment by davidmrau** [comment]
Please reopen if anything is unclear.
