### ISSUE TITLE
Issue with gates parameters

### ISSUE THREAD

**Issue by elias-ramzi** [davidmrau/mixture-of-experts#12]
Hi,

Thank you for this repo!

I think there is an issue with the gates parameters defined in the MoE as:
```
self.w_gate = nn.Parameter(torch.zeros(input_size, num_experts), requires_grad=True).to(self.device)
self.w_noise = nn.Parameter(torch.zeros(input_size, num_experts), requires_grad=True).to(self.device)
```
In my version of torch (1.11.0) applying `.to(self.device)` to a `nn.Parameter` returns a `nn.Tensor`, so the weights are not learned during training.
A simple fix is to juste remove the `.to(self.device)` as the gates weights are registered by `torch` as model parameters and can be set to the correct device outside of the `__init__`.
Again I don't know if this is specific to my `torch` version, but this prohibited learning the MoE for me.

Hope this helps!

**Comment by sofiapvcp** [comment]
Hi, I think 
`self.w_gate = nn.Parameter(torch.zeros(input_size, num_experts), requires_grad=True,device=self.device))`
will do the trick


source: https://github.com/pytorch/pytorch/issues/17484

**Comment by elias-ramzi** [comment]
Hi, this would indeed work. However passing the device is not even necessary as this can be done from outside the class definition by calling `.to(device)` on the instantiated module.

**Comment by davidmrau** [comment]
great that you guys found a solution. Would you create a pull request so others can benefit from your solution as well? :)

**Comment by elias-ramzi** [comment]
Hi, I would be happy to do that!

**Comment by davidmrau** [comment]
Thanks a lot!
