### ISSUE TITLE
multiple_by_gates after exp

### ISSUE THREAD

**Issue by yjw1029** [davidmrau/mixture-of-experts#15]
Hi,

Thank for your pytorch implementation of sparse MOE! In the combine method of SparseDispatcher, the stitched is transformed by exp and then multiply_by_gates. I wonder if the stitched should be first multiplied by gates and then transformed by exp, which is consistent with the [tf implementation](https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/expert_utils.py#L810).
```python
def combine(self, expert_out, multiply_by_gates=True):
        # apply exp to expert outputs, so we are not longer in log space
        stitched = torch.cat(expert_out, 0).exp()

        if multiply_by_gates:
            stitched = stitched.mul(self._nonzero_gates)
```

**Comment by davidmrau** [comment]
If we were to stay in log space we would have to add the stitched with the gates (equivalent to multiplying in normal space ). Therefore, I believe the implementation is correct.

**Comment by davidmrau** [comment]
see https://github.com/davidmrau/mixture-of-experts/issues/4#issuecomment-567124805
