### ISSUE TITLE
regression task self.w_gate is nan

### ISSUE THREAD

**Issue by JieDengsc** [davidmrau/mixture-of-experts#16]
After I changed the code to a regression task, self.w_gate showed Nan after 5 epochs.

**Comment by davidmrau** [comment]
i'll have a look!

**Comment by JieDengsc** [comment]
> i'll have a look!

Thank you for your reply. For regression tasks, my modifications are as follows:
1. loss_fn = nn.MSELoss()
2. MLP: out = self.fc2(out)

I used your "example.py" to modify it to the regression type label, which can be trained correctly. However, once replaced with my dataset, after training 5 epoch, the problem of “self.w_gate = nan” occurs.

I don't know if I made a mistake, or if some of the functions inside need to be further modified.

**Comment by davidmrau** [comment]
Sorry, what dataset are you using exactly in order to be able to reproduce the error?

**Comment by davidmrau** [comment]
Please reopen if still not resolved
