### ISSUE TITLE
Why is weighted sum calculated in the logarithmic space?

### ISSUE THREAD

**Issue by XieWeikai** [davidmrau/mixture-of-experts#21]
In the implementation of combine in class SparseDispatcher, the code first apply exp(), then calculate weighted sum and finally go back to log space. Why to do that? I think the result is not as same as the original paper.
In the paper, we have
y = sum(G(x) * E(x))
but in your code, I think you calculate
y = log(sum(G(x) * exp(E(X)) ) )
It seems not the same

**Comment by davidmrau** [comment]
Please have a look at https://github.com/davidmrau/mixture-of-experts/issues/4

**Comment by davidmrau** [comment]
fixed
