### ISSUE TITLE
have you ever meet such trend of loss ?

### ISSUE THREAD

**Issue by lonelyqian** [davidmrau/mixture-of-experts#22]
![image-20231211111947197](https://github.com/davidmrau/mixture-of-experts/assets/72489518/4139b6a3-3bfd-4cdb-87bb-20877cd47eb1)

**Comment by lonelyqian** [comment]
after the 24k iterations , the distribution of the experts becomes extremely unbalanced and loss increases rapidly

**Comment by davidmrau** [comment]
I have not. What are you training on exactly?

**Comment by lonelyqian** [comment]
just a simple image segment task

**Comment by davidmrau** [comment]
Have you investigated the problem? Perhaps exploding gradients? Have you tried clipping the gradients?
