### ISSUE TITLE
MoE for transformers

### ISSUE THREAD

**Issue by elias-ramzi** [davidmrau/mixture-of-experts#24]
Hi,

I want to use the MoE inside a transformer model. So instead on the current input size of shape `[batch_size, input_size]` I have an input size of size `[batch_size, sequence_length, input_size]`. Do you know how can I make this work?

Best,
Elias

**Comment by Mr-lonely0** [comment]
Hi, Elias!

I met with the same trouble. Have you solved this problem?

Best regards : )
