### ISSUE TITLE
Examples of using real dataset

### ISSUE THREAD

**Issue by GabrielLin** [davidmrau/mixture-of-experts#3]
Could you please provide examples of using real datasets? Realy thanks.

**Comment by davidmrau** [comment]
Implementation wise there shouldn't be any difference in using a real dataset. Do you have a dataset in mind that I could provide an example for?

**Comment by GabrielLin** [comment]
Merry Christmas!

Sorry to the late reply. I missed the notification. 

What about CIFAR-10 http://www.cs.utoronto.ca/~kriz/cifar.html or  fashion-mnist 
 https://github.com/zalandoresearch/fashion-mnist ?

Thanks.

**Comment by davidmrau** [comment]
Hi. In case it is still relevant for you. I added the CIFAR 10 dataset here: https://github.com/davidmrau/mixture-of-experts/blob/master/cifar10_example.py

**Comment by GabrielLin** [comment]
Really thanks.
