### ISSUE TITLE
Incompatibility with pytorch > pytorch 1.1

### ISSUE THREAD

**Issue by StillerPatrick** [davidmrau/mixture-of-experts#5]
Hey, 

your code is incompatible with pytorch > 1.1 cause of change in the nonzero function that you are using. I found a workaround by compile pytorch by myself. 

The changes are descriped in:
https://github.com/pytorch/pytorch/commit/3c8ce2a57e8be913a6d3209fc8b0a8225d7234df

Cheers,
Patrick

**Comment by davidmrau** [comment]
Hey Parick, Thanks a lot for pointing this out.
Cheers,
David
